version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: cmd/rest/Dockerfile
      args:
        SERVICE: rest
    command: go run cmd/rest/main.go
    depends_on:
      - db
    ports:
      - "8080:8080"
  grpc:
    build:
      context: .
      dockerfile: cmd/grpc/Dockerfile
      args:
        SERVICE: grpc
    command: go run cmd/grpc/main.go
    depends_on:
      - db
    ports:
      - "50051:50051"
  graphql:
    build:
      context: .
      dockerfile: cmd/graphql/Dockerfile
      args:
        SERVICE: graphql
    command: go run cmd/graphql/main.go
    depends_on:
      - db
    ports:
      - "8081:8081"
