// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Order struct {
	ID           string    `json:"id"`
	CustomerName string    `json:"customerName"`
	Amount       float64   `json:"amount"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Query struct {
}
